export { default as Main } from './main/Main'
export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Menu } from './menu/Menu'
export { default as DishDetail } from './dishDetail/DishDetail'